# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-aeroboard"
BBFILE_PATTERN_meta-aeroboard = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-aeroboard = "6"

LAYERDEPENDS_meta-aeroboard = "core"
LAYERSERIES_COMPAT_meta-aeroboard = "dunfell"
